#!/bin/sh

### BEGIN INIT INFO
# Provides:          sleep-monitor
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Sleep Monitor
# Description:       Baby Sleep Monitor
### END INIT INFO

. /lib/lsb/init-functions

SCRIPT=`realpath $0`
SCRIPT_DIR=`dirname $SCRIPT`
INSTALL_DIR=`realpath ${SCRIPT_DIR}/..`

test -f ${INSTALL_DIR}/SleepMonitor.py || exit 0

start() {
    log_daemon_msg "Starting Sleep Monitor server" "sleepmonitor"
    start-stop-daemon --start --quiet --oknodo \
        --chdir ${INSTALL_DIR} \
        --exec /usr/bin/python \
        --background --make-pidfile \
        --pidfile /var/run/sleepmonitor.pid \
        -- SleepMonitor.py
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping Sleep Monitor server" "sleepmonitor"
    start-stop-daemon --stop --quiet --oknodo \
        --pidfile /var/run/sleepmonitor.pid \
        --remove-pidfile \
        --retry=TERM/30/KILL/5
    log_end_msg $?
}

case "$1" in
    start)
        start;
        ;;
    stop)
        stop;
        ;;
    reload|force-reload)
        log_action_msg "Nothing to do"
        ;;
    restart)
        stop;
        start;
        ;;
    status)
        log_action_msg "Not implemented yet"
        ;;

    *)
        log_action_msg "Usage: /etc/init.d/sleep-monitor {start|stop|reload|force-reload|restart|try-restart|status}" || true
        exit 1
esac
